// <auto-generated />
using System;
using BubbaBag.Modules.Inventario.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BubbaBag.Modules.Inventario.Infrastructure.Migrations
{
    [DbContext(typeof(InventarioDbContext))]
    [Migration("20260922034301_AgregarControlSeriadosYMovimientos")]
    partial class AgregarControlSeriadosYMovimientos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("inventario")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("RecursoTecnicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("RecursoTecnicoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Almacenes", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Almacenes.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenOrigenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemSeriadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioResponsableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenDestinoId");

                    b.HasIndex("AlmacenOrigenId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaMovimiento");

                    b.HasIndex("ItemSeriadoId");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("Tipo");

                    b.ToTable("MovimientosInventario", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Almacenes.StockAlmacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("CantidadReservada")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("AlmacenId", "ProductoId")
                        .IsUnique();

                    b.ToTable("StocksAlmacen", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Productos.ItemSeriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenActualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteActualId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroSmartCard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OrdenTrabajoInstalacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenActualId");

                    b.HasIndex("ClienteActualId");

                    b.HasIndex("Estado");

                    b.HasIndex("MacAddress");

                    b.HasIndex("NumeroSerie")
                        .IsUnique();

                    b.HasIndex("NumeroSmartCard");

                    b.HasIndex("OrdenTrabajoInstalacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsSeriados", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Productos.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CatalogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EsSerializado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Productos", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Almacenes.MovimientoInventario", b =>
                {
                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Almacenes.Almacen", "AlmacenDestino")
                        .WithMany()
                        .HasForeignKey("AlmacenDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Almacenes.Almacen", "AlmacenOrigen")
                        .WithMany()
                        .HasForeignKey("AlmacenOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Productos.ItemSeriado", "ItemSeriado")
                        .WithMany()
                        .HasForeignKey("ItemSeriadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlmacenDestino");

                    b.Navigation("AlmacenOrigen");

                    b.Navigation("ItemSeriado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Almacenes.StockAlmacen", b =>
                {
                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Almacenes.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Productos.ItemSeriado", b =>
                {
                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Almacenes.Almacen", "AlmacenActual")
                        .WithMany()
                        .HasForeignKey("AlmacenActualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.Inventario.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlmacenActual");

                    b.Navigation("Producto");
                });
#pragma warning restore 612, 618
        }
    }
}
