// <auto-generated />
using System;
using BubbaBag.Modules.ServicioCampo.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BubbaBag.Modules.ServicioCampo.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ServicioCampoDbContext))]
    [Migration("20260925172424_AgregarCamposD365Producto")]
    partial class AgregarCamposD365Producto
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("serviciocampo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BubbaBag.Modules.RecursosHumanos.Domain.Organizacion.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("EsSedePrincipal")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sucursales", "rrhh", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("RecursoTecnicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("RecursoTecnicoId");

                    b.HasIndex("SucursalId");

                    b.ToTable("Almacenes", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.MovimientoInventario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenOrigenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaMovimiento")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemSeriadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroDocumento")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("UsuarioResponsableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenDestinoId");

                    b.HasIndex("AlmacenOrigenId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("FechaMovimiento");

                    b.HasIndex("ItemSeriadoId");

                    b.HasIndex("NumeroDocumento");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("ProductoId");

                    b.HasIndex("Tipo");

                    b.ToTable("MovimientosInventario", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.StockAlmacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadDisponible")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<decimal>("CantidadReservada")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductoId");

                    b.HasIndex("AlmacenId", "ProductoId")
                        .IsUnique();

                    b.ToTable("StocksAlmacen", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal?>("CoordenadaLat")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<decimal?>("CoordenadaLng")
                        .HasPrecision(10, 7)
                        .HasColumnType("numeric(10,7)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("EsClienteFacturacion")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsClienteServicio")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ReferenciaUbicacion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("TelefonoPrincipal")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TelefonoSecundario")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("DNI");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("NATURAL");

                    b.Property<string>("UbigeoCodigo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoCliente")
                        .IsUnique();

                    b.HasIndex("DocumentoIdentidad");

                    b.HasIndex("UbigeoCodigo");

                    b.ToTable("clientes", "crm");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CampoDefinicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("boolean");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OpcionesJson")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDato")
                        .HasColumnType("integer");

                    b.Property<Guid>("TipoOrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipoOrdenTrabajoId", "Clave")
                        .IsUnique();

                    b.ToTable("CamposDefinicion", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ambito");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("MotivosIncidencia", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#0f6cbd");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("ExigeEvidenciasFotograficas")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExigeFirmaCliente")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereVisitaCampo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposOrdenTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoTarea")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFacturacionId", "CodigoTarea")
                        .IsUnique();

                    b.ToTable("TiposTareaServicio", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.LiquidacionMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlmacenId")
                        .HasColumnType("uuid");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasDefaultValue("Borrador");

                    b.Property<DateTime>("FechaLiquidacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NumeroLiquidacion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ResponsableId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenId");

                    b.HasIndex("NumeroLiquidacion")
                        .IsUnique();

                    b.HasIndex("OrdenTrabajoId");

                    b.ToTable("LiquidacionesMaterial", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.LiquidacionMaterialItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadConsumida")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CantidadDevuelta")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("EsRetiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsSeriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("ItemSeriadoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("LiquidacionMaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("LiquidacionMaterialId");

                    b.HasIndex("NumeroSerie");

                    b.HasIndex("ProductoId");

                    b.ToTable("LiquidacionesMaterialItems", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.MaterialTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadPrevista")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CantidadUtilizada")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<bool>("EsRetiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("EsSeriado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemSeriadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroSmartCard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrabajoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("NumeroSerie");

                    b.HasIndex("ProductoId");

                    b.HasIndex("TrabajoId");

                    b.ToTable("MaterialesTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteServicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoContrato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoWo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ContadorOmisionDescarga")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DescargaMaterialesConfirmada")
                        .HasColumnType("boolean");

                    b.Property<bool>("DescargaMaterialesObligatoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("DescargaMaterialesOmitida")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoSistema")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaDescargaMateriales")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotivoCierreId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoOmisionMateriales")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("NoConsumioMateriales")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroOrden")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroPedido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ReferenciaExterna")
                        .HasColumnType("text");

                    b.Property<Guid>("TipoOrdenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ZonaOperativaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFacturacionId");

                    b.HasIndex("ClienteServicioId");

                    b.HasIndex("CodigoContrato");

                    b.HasIndex("CodigoWo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("EstadoSistema");

                    b.HasIndex("MotivoCierreId");

                    b.HasIndex("NumeroOrden");

                    b.HasIndex("TipoOrdenId");

                    b.HasIndex("ZonaOperativaId");

                    b.ToTable("OrdenesTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<bool>("EsRetiro")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemSeriadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroSmartCard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrdenTrabajoVisitaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("ItemSeriadoId");

                    b.HasIndex("NumeroSerie");

                    b.HasIndex("NumeroSmartCard");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("OrdenTrabajoVisitaId");

                    b.ToTable("OrdenTrabajoMateriales", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoTarea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsElegibleBonoIndicador")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoTarea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ItemNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("MontoBonoFinal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<decimal>("MontoPenalizacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<Guid?>("MotivoRechazoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreReglaAplicada")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroWoIbs")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionesRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TarifaBaseCongelada")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid>("TipoTareaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTarea")
                        .IsUnique();

                    b.HasIndex("MotivoRechazoId");

                    b.HasIndex("NumeroWoIbs");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("TipoTareaId");

                    b.ToTable("OrdenTrabajoTareas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloqueHorario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoVisita")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DniFirmante")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("EvidenciasConfirmadas")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaSalidaEnCamino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinAgendado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaClienteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirmadoPor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("InicioAgendado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotivoCancelacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreFirmante")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroCita")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumeroVisita")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroVisitaOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ObservacionesCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionesTecnico")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecursoTecnicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVisita")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("MotivoCancelacionId");

                    b.HasIndex("NumeroCita");

                    b.HasIndex("NumeroVisitaOrigen");

                    b.HasIndex("RecursoTecnicoId");

                    b.HasIndex("OrdenTrabajoId", "NumeroVisita")
                        .IsUnique();

                    b.ToTable("OrdenTrabajoVisitas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisitaEvidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoordenadasGps")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdenTrabajoVisitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoVisitaId");

                    b.ToTable("OrdenTrabajoVisitaEvidencias", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.TareaTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsObligatoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<string>("EvidenciaUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreTarea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ObservacionesTecnico")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrdenSecuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid?>("PlantillaTareaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiereEvidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid?>("TareaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TrabajoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TareaId");

                    b.HasIndex("TrabajoId");

                    b.ToTable("TareasTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.Trabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoTrabajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaFin")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PlantillaTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TarifaBaseCongelada")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.HasIndex("PlantillaTrabajoId");

                    b.HasIndex("ServicioId");

                    b.HasIndex("OrdenTrabajoId", "CodigoTrabajo")
                        .IsUnique();

                    b.ToTable("Trabajos", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadPrevista")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<bool>("EsObligatorio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Observaciones")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<Guid>("PlantillaTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaTrabajoId");

                    b.HasIndex("ProductoId");

                    b.ToTable("PlantillasMateriales", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EsObligatoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Instrucciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrdenSecuencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<Guid>("PlantillaTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<bool>("RequiereEvidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("TareaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlantillaTrabajoId");

                    b.HasIndex("TareaId");

                    b.ToTable("PlantillasTareas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<bool>("EsPredeterminada")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ServicioId");

                    b.ToTable("PlantillasTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.Tarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("RequiereEvidenciaFotografica")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Tareas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Productos.CategoriaProducto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Familia")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("CategoriasProducto", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Productos.ItemSeriado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenActualId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ClienteActualId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("FechaInstalacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroSerie")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroSmartCard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid?>("OrdenTrabajoInstalacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenActualId");

                    b.HasIndex("ClienteActualId");

                    b.HasIndex("Estado");

                    b.HasIndex("MacAddress");

                    b.HasIndex("NumeroSerie")
                        .IsUnique();

                    b.HasIndex("NumeroSmartCard");

                    b.HasIndex("OrdenTrabajoInstalacionId");

                    b.HasIndex("ProductoId");

                    b.ToTable("ItemsSeriados", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Productos.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AfectoImpuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("CatalogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoBarras")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("ConvertirEnActivoCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("CostoActual")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("CostoEstandar")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("EsSerializado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Notas")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("PrecioBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("ProveedorDefecto")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Productos", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Productos.ProductoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoExterno")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Servicios", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Productos.UnidadMedida", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("PermiteDecimales")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("UnidadesMedida", "inventario");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Recursos.RecursoTecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("AlmacenBaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenMovilId")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacidadMaximaOrdenesPorDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorHex")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("#0078d4");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZonaOperativaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenBaseId");

                    b.HasIndex("AlmacenMovilId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaOperativaId");

                    b.ToTable("RecursosTecnicos", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Recursos.ZonaOperativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("AlmacenPredeterminadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DescripcionProveedor")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenPredeterminadoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SucursalId");

                    b.ToTable("ZonasOperativas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Ubigeos.Ubigeo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("CapitalLegal")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("CodigoRegionNatural")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Distrito")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Provincia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RegionNatural")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Codigo");

                    b.HasIndex("Departamento");

                    b.HasIndex("Departamento", "Provincia");

                    b.ToTable("ubigeos", "crm");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.MovimientoInventario", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.Almacen", "AlmacenDestino")
                        .WithMany()
                        .HasForeignKey("AlmacenDestinoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.Almacen", "AlmacenOrigen")
                        .WithMany()
                        .HasForeignKey("AlmacenOrigenId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.ItemSeriado", "ItemSeriado")
                        .WithMany()
                        .HasForeignKey("ItemSeriadoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlmacenDestino");

                    b.Navigation("AlmacenOrigen");

                    b.Navigation("ItemSeriado");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.StockAlmacen", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Clientes.Cliente", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Ubigeos.Ubigeo", "Ubigeo")
                        .WithMany()
                        .HasForeignKey("UbigeoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ubigeo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CampoDefinicion", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", null)
                        .WithMany("CamposDefinicion")
                        .HasForeignKey("TipoOrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteFacturacion");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.LiquidacionMaterial", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.Almacen", "Almacen")
                        .WithMany()
                        .HasForeignKey("AlmacenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("LiquidacionesMaterial")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Almacen");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.LiquidacionMaterialItem", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.LiquidacionMaterial", "LiquidacionMaterial")
                        .WithMany("Items")
                        .HasForeignKey("LiquidacionMaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LiquidacionMaterial");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.MaterialTrabajo", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.Trabajo", "Trabajo")
                        .WithMany("Materiales")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Producto");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Clientes.Cliente", "ClienteServicio")
                        .WithMany()
                        .HasForeignKey("ClienteServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoCierre")
                        .WithMany()
                        .HasForeignKey("MotivoCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", "TipoOrden")
                        .WithMany()
                        .HasForeignKey("TipoOrdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Recursos.ZonaOperativa", "ZonaOperativa")
                        .WithMany()
                        .HasForeignKey("ZonaOperativaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteFacturacion");

                    b.Navigation("ClienteServicio");

                    b.Navigation("MotivoCierre");

                    b.Navigation("TipoOrden");

                    b.Navigation("ZonaOperativa");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoMaterial", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Materiales")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", "OrdenTrabajoVisita")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoVisitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("OrdenTrabajoVisita");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoTarea", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoRechazo")
                        .WithMany()
                        .HasForeignKey("MotivoRechazoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Tareas")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", "TipoTarea")
                        .WithMany()
                        .HasForeignKey("TipoTareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotivoRechazo");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("TipoTarea");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoCancelacion")
                        .WithMany()
                        .HasForeignKey("MotivoCancelacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Visitas")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Recursos.RecursoTecnico", "RecursoTecnico")
                        .WithMany()
                        .HasForeignKey("RecursoTecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotivoCancelacion");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("RecursoTecnico");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisitaEvidencia", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", "OrdenTrabajoVisita")
                        .WithMany("Evidencias")
                        .HasForeignKey("OrdenTrabajoVisitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajoVisita");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.TareaTrabajo", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.Trabajo", "Trabajo")
                        .WithMany("Tareas")
                        .HasForeignKey("TrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tarea");

                    b.Navigation("Trabajo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.Trabajo", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Trabajos")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTrabajo", "PlantillaTrabajo")
                        .WithMany()
                        .HasForeignKey("PlantillaTrabajoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.ProductoServicio", "Servicio")
                        .WithMany()
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("PlantillaTrabajo");

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaMaterial", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTrabajo", "PlantillaTrabajo")
                        .WithMany("Materiales")
                        .HasForeignKey("PlantillaTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantillaTrabajo");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTarea", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTrabajo", "PlantillaTrabajo")
                        .WithMany("Tareas")
                        .HasForeignKey("PlantillaTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.Tarea", "Tarea")
                        .WithMany()
                        .HasForeignKey("TareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlantillaTrabajo");

                    b.Navigation("Tarea");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTrabajo", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.ProductoServicio", "Servicio")
                        .WithMany("Plantillas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Servicio");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Productos.ItemSeriado", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Almacenes.Almacen", "AlmacenActual")
                        .WithMany()
                        .HasForeignKey("AlmacenActualId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Productos.Producto", "Producto")
                        .WithMany()
                        .HasForeignKey("ProductoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AlmacenActual");

                    b.Navigation("Producto");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Recursos.RecursoTecnico", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Recursos.ZonaOperativa", "ZonaOperativa")
                        .WithMany()
                        .HasForeignKey("ZonaOperativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ZonaOperativa");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", b =>
                {
                    b.Navigation("CamposDefinicion");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.LiquidacionMaterial", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.Navigation("LiquidacionesMaterial");

                    b.Navigation("Materiales");

                    b.Navigation("Tareas");

                    b.Navigation("Trabajos");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.Trabajo", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Plantillas.PlantillaTrabajo", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Tareas");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Productos.ProductoServicio", b =>
                {
                    b.Navigation("Plantillas");
                });
#pragma warning restore 612, 618
        }
    }
}
