// <auto-generated />
using System;
using BubbaBag.Modules.ServicioCampo.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BubbaBag.Modules.ServicioCampo.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ServicioCampoDbContext))]
    [Migration("20260913231901_ConfiguracionEvidenciasYMotivosServicioCampo")]
    partial class ConfiguracionEvidenciasYMotivosServicioCampo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("serviciocampo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("CoordenadaLat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CoordenadaLng")
                        .HasColumnType("numeric");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EsClienteFacturacion")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsClienteServicio")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaUbicacion")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoSecundario")
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UbigeoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("clientes", "crm", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ambito");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("MotivosIncidencia", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.OrigenOrden", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("EsIntegracionExterna")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("OrigenesOrden", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#0f6cbd");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("ExigeEvidenciasFotograficas")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<bool>("ExigeFirmaCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereVisitaCampo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("TiposOrdenTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoTarea")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer");

                    b.Property<bool>("EsTareaSiebel")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTarea")
                        .IsUnique();

                    b.ToTable("TiposTareaServicio", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteServicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoContratoIbs")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoWo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ContadorOmisionDescarga")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DescargaMaterialesConfirmada")
                        .HasColumnType("boolean");

                    b.Property<bool>("DescargaMaterialesObligatoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("DescargaMaterialesOmitida")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoSistema")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaDescargaMateriales")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IdEncabezadoExterno")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("MotivoCierreId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoOmisionMateriales")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("NoConsumioMateriales")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroOrdenExterna")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrigenOrdenId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoOrdenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFacturacionId");

                    b.HasIndex("ClienteServicioId");

                    b.HasIndex("CodigoContratoIbs");

                    b.HasIndex("CodigoWo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("EstadoSistema");

                    b.HasIndex("MotivoCierreId");

                    b.HasIndex("NumeroOrdenExterna");

                    b.HasIndex("OrigenOrdenId");

                    b.HasIndex("TipoOrdenId");

                    b.ToTable("OrdenesTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsElegibleBonoIndicador")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoTarea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ItemNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("MontoBonoFinal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<decimal>("MontoPenalizacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<Guid?>("MotivoRechazoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreReglaAplicada")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroWoIbs")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionesRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TarifaBaseCongelada")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("TarifarioReglaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoTareaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MotivoRechazoId");

                    b.HasIndex("NumeroWoIbs");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("TarifarioReglaId");

                    b.HasIndex("TipoTareaId");

                    b.ToTable("OrdenTrabajoTareas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloqueHorario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CuadrillaTecnicoId")
                        .HasColumnType("uuid");

                    b.Property<string>("DniFirmante")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("EvidenciasConfirmadas")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaSalidaEnCamino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinAgendado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaClienteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirmadoPor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("InicioAgendado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotivoCancelacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreFirmante")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("NumeroVisita")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroVisitaSiebel")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NumeroVisitaToa")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ObservacionesCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionesTecnico")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CuadrillaTecnicoId");

                    b.HasIndex("Estado");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("MotivoCancelacionId");

                    b.HasIndex("NumeroVisitaSiebel");

                    b.HasIndex("NumeroVisitaToa");

                    b.HasIndex("OrdenTrabajoId", "NumeroVisita")
                        .IsUnique();

                    b.ToTable("OrdenTrabajoVisitas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisitaEvidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoordenadasGps")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdenTrabajoVisitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoVisitaId");

                    b.ToTable("OrdenTrabajoVisitaEvidencias", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("FechaVigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVigenciaHasta")
                        .HasColumnType("date");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("PEN");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ClienteFacturacionId", "FechaVigenciaDesde", "FechaVigenciaHasta");

                    b.ToTable("Tarifarios", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AplicaBonoIndicador")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MontoTarifaBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NombreRegla")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<Guid>("TarifarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoTareaServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TarifarioId");

                    b.HasIndex("TipoTareaServicioId");

                    b.ToTable("TarifarioReglas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioReglaCriterio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CampoOrdenTrabajo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OperadorComparacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("IGUAL");

                    b.Property<Guid>("TarifarioReglaId")
                        .HasColumnType("uuid");

                    b.Property<string>("ValorEsperado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("TarifarioReglaId", "CampoOrdenTrabajo");

                    b.ToTable("TarifarioReglaCriterios", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteServicio")
                        .WithMany()
                        .HasForeignKey("ClienteServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoCierre")
                        .WithMany()
                        .HasForeignKey("MotivoCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.OrigenOrden", "OrigenOrden")
                        .WithMany()
                        .HasForeignKey("OrigenOrdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", "TipoOrden")
                        .WithMany()
                        .HasForeignKey("TipoOrdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteFacturacion");

                    b.Navigation("ClienteServicio");

                    b.Navigation("MotivoCierre");

                    b.Navigation("OrigenOrden");

                    b.Navigation("TipoOrden");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoTarea", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoRechazo")
                        .WithMany()
                        .HasForeignKey("MotivoRechazoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Tareas")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", "TarifarioRegla")
                        .WithMany()
                        .HasForeignKey("TarifarioReglaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", "TipoTarea")
                        .WithMany()
                        .HasForeignKey("TipoTareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotivoRechazo");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("TarifarioRegla");

                    b.Navigation("TipoTarea");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoCancelacion")
                        .WithMany()
                        .HasForeignKey("MotivoCancelacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Visitas")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MotivoCancelacion");

                    b.Navigation("OrdenTrabajo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisitaEvidencia", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", "OrdenTrabajoVisita")
                        .WithMany("Evidencias")
                        .HasForeignKey("OrdenTrabajoVisitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajoVisita");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", b =>
                {
                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteFacturacion");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", "Tarifario")
                        .WithMany("Reglas")
                        .HasForeignKey("TarifarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", "TipoTareaServicio")
                        .WithMany()
                        .HasForeignKey("TipoTareaServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tarifario");

                    b.Navigation("TipoTareaServicio");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioReglaCriterio", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", "TarifarioRegla")
                        .WithMany("Criterios")
                        .HasForeignKey("TarifarioReglaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TarifarioRegla");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.Navigation("Tareas");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", b =>
                {
                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", b =>
                {
                    b.Navigation("Criterios");
                });
#pragma warning restore 612, 618
        }
    }
}
