// <auto-generated />
using System;
using BubbaBag.Modules.ServicioCampo.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BubbaBag.Modules.ServicioCampo.Infrastructure.Database.Migrations
{
    [DbContext(typeof(ServicioCampoDbContext))]
    [Migration("20260922034342_AgregarMaterialesAOrdenTrabajo")]
    partial class AgregarMaterialesAOrdenTrabajo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("serviciocampo")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Apellidos")
                        .HasColumnType("text");

                    b.Property<string>("CodigoCliente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("CoordenadaLat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("CoordenadaLng")
                        .HasColumnType("numeric");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DocumentoIdentidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EsClienteFacturacion")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsClienteServicio")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonSocial")
                        .HasColumnType("text");

                    b.Property<string>("ReferenciaUbicacion")
                        .HasColumnType("text");

                    b.Property<string>("TelefonoPrincipal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelefonoSecundario")
                        .HasColumnType("text");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoPersona")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UbigeoCodigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("clientes", "crm", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Almacenes.Almacen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RecursoTecnicoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SucursalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Almacenes", "inventario", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BubbaBag.Modules.Inventario.Domain.Productos.Producto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CatalogoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<bool>("EsSerializado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PrecioBase")
                        .HasColumnType("numeric");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Productos", "inventario", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BubbaBag.Modules.RecursosHumanos.Domain.Organizacion.Sucursal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<bool>("EsSedePrincipal")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sucursales", "rrhh", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CampoDefinicion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("boolean");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OpcionesJson")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("OrdenVisual")
                        .HasColumnType("integer");

                    b.Property<int>("TipoDato")
                        .HasColumnType("integer");

                    b.Property<Guid>("TipoOrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TipoOrdenTrabajoId", "Clave")
                        .IsUnique();

                    b.ToTable("CamposDefinicion", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CatalogoServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClienteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Nombre");

                    b.ToTable("CatalogosServicio", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Ambito")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Ambito");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("MotivosIncidencia", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.Servicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CatalogoServicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoExterno")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("PrecioBase")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m);

                    b.Property<Guid?>("ProductoComercialId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CatalogoServicioId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Servicios", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.ServicioMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("CantidadTeorica")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId", "ProductoId");

                    b.ToTable("ServicioMateriales", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.ServicioPaso", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("EsObligatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("NumeroPaso")
                        .HasColumnType("integer");

                    b.Property<bool>("RequiereFoto")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.Property<int>("TipoEvidencia")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId", "NumeroPaso");

                    b.ToTable("ServicioPasos", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.SucursalServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ServicioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ServicioId");

                    b.HasIndex("SucursalId", "ServicioId")
                        .IsUnique();

                    b.ToTable("SucursalesServicio", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("ColorHex")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#0f6cbd");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("ExigeEvidenciasFotograficas")
                        .HasColumnType("boolean");

                    b.Property<bool>("ExigeFirmaCliente")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("RequiereVisitaCampo")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("TiposOrdenTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoTarea")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("DuracionEstimadaMinutos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFacturacionId", "CodigoTarea")
                        .IsUnique();

                    b.ToTable("TiposTareaServicio", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClienteServicioId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoContrato")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CodigoWo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ContadorOmisionDescarga")
                        .HasColumnType("integer");

                    b.Property<Guid>("CreadoPorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("DescargaMaterialesConfirmada")
                        .HasColumnType("boolean");

                    b.Property<bool>("DescargaMaterialesObligatoria")
                        .HasColumnType("boolean");

                    b.Property<bool>("DescargaMaterialesOmitida")
                        .HasColumnType("boolean");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("EstadoOrigen")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EstadoSistema")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("FechaDescargaMateriales")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotivoCierreId")
                        .HasColumnType("uuid");

                    b.Property<string>("MotivoOmisionMateriales")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("NoConsumioMateriales")
                        .HasColumnType("boolean");

                    b.Property<string>("NumeroOrden")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroPedido")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("TipoOrdenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ZonaOperativaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFacturacionId");

                    b.HasIndex("ClienteServicioId");

                    b.HasIndex("CodigoContrato");

                    b.HasIndex("CodigoWo")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("EstadoSistema");

                    b.HasIndex("MotivoCierreId");

                    b.HasIndex("NumeroOrden");

                    b.HasIndex("TipoOrdenId");

                    b.HasIndex("ZonaOperativaId");

                    b.ToTable("OrdenesTrabajo", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Cantidad")
                        .HasPrecision(14, 2)
                        .HasColumnType("numeric(14,2)");

                    b.Property<bool>("EsRetiro")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ItemSeriadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NumeroSerie")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("NumeroSmartCard")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("OrdenTrabajoVisitaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FechaRegistro");

                    b.HasIndex("ItemSeriadoId");

                    b.HasIndex("NumeroSerie");

                    b.HasIndex("NumeroSmartCard");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("OrdenTrabajoVisitaId");

                    b.ToTable("OrdenTrabajoMateriales", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoTarea", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoTarea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("EsElegibleBonoIndicador")
                        .HasColumnType("boolean");

                    b.Property<string>("EstadoTarea")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("ItemNumero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("MontoBonoFinal")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<decimal>("MontoPenalizacion")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasDefaultValue(0.00m);

                    b.Property<Guid?>("MotivoRechazoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreReglaAplicada")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroWoIbs")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ObservacionesCierre")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionesRechazo")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TarifaBaseCongelada")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("TarifarioReglaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoTareaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoTarea")
                        .IsUnique();

                    b.HasIndex("MotivoRechazoId");

                    b.HasIndex("NumeroWoIbs");

                    b.HasIndex("OrdenTrabajoId");

                    b.HasIndex("TarifarioReglaId");

                    b.HasIndex("TipoTareaId");

                    b.ToTable("OrdenTrabajoTareas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BloqueHorario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("CodigoVisita")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DniFirmante")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<bool>("EvidenciasConfirmadas")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("FechaFinReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaInicioReal")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<DateTime?>("FechaSalidaEnCamino")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaSincronizacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FinAgendado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirmaClienteUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("FirmadoPor")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("InicioAgendado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotivoCancelacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreFirmante")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("NumeroCita")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("NumeroVisita")
                        .HasColumnType("integer");

                    b.Property<string>("NumeroVisitaOrigen")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ObservacionesCancelacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ObservacionesTecnico")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("OrdenTrabajoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RecursoTecnicoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CodigoVisita")
                        .IsUnique();

                    b.HasIndex("Estado");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("MotivoCancelacionId");

                    b.HasIndex("NumeroCita");

                    b.HasIndex("NumeroVisitaOrigen");

                    b.HasIndex("RecursoTecnicoId");

                    b.HasIndex("OrdenTrabajoId", "NumeroVisita")
                        .IsUnique();

                    b.ToTable("OrdenTrabajoVisitas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisitaEvidencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CoordenadasGps")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsObligatoria")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observaciones")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrdenTrabajoVisitaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("OrdenTrabajoVisitaId");

                    b.ToTable("OrdenTrabajoVisitaEvidencias", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Recursos.RecursoTecnico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("AlmacenBaseId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AlmacenMovilId")
                        .HasColumnType("uuid");

                    b.Property<int>("CapacidadMaximaOrdenesPorDia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(6);

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ColorHex")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasDefaultValue("#0078d4");

                    b.Property<string>("DocumentoIdentidad")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid?>("EmpleadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid?>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ZonaOperativaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenBaseId");

                    b.HasIndex("AlmacenMovilId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("EmpleadoId");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("ZonaOperativaId");

                    b.ToTable("RecursosTecnicos", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Recursos.ZonaOperativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid?>("AlmacenPredeterminadoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("DescripcionProveedor")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("SucursalId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AlmacenPredeterminadoId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("SucursalId");

                    b.ToTable("ZonasOperativas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifaServicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaGarantia")
                        .HasColumnType("boolean");

                    b.Property<bool>("AplicaPago")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoServicio")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("DetalleServicio")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmpresaContratante")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("FijoAdicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FijoBase")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Indicador1_Adicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Indicador1_CycleTime")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Indicador2_Adicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Indicador2_Agenda")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Indicador3_Adicional")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Indicador3_Sin30")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("MontoTotalTeorico")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("Puntos")
                        .HasColumnType("integer");

                    b.Property<string>("Sucursal")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("Tipificacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("TipoTareaServicioId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("VariableAdicionalTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("VariableTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteFacturacionId");

                    b.HasIndex("TipoTareaServicioId");

                    b.HasIndex("EmpresaContratante", "CodigoServicio", "Sucursal");

                    b.ToTable("TarifasServicio", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ClienteFacturacionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateOnly>("FechaVigenciaDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaVigenciaHasta")
                        .HasColumnType("date");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasDefaultValue("PEN");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.HasIndex("ClienteFacturacionId", "FechaVigenciaDesde", "FechaVigenciaHasta");

                    b.ToTable("Tarifarios", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AplicaBonoIndicador")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MontoTarifaBase")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("NombreRegla")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Prioridad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<Guid>("TarifarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TipoTareaServicioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TarifarioId");

                    b.HasIndex("TipoTareaServicioId");

                    b.ToTable("TarifarioReglas", "serviciocampo");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CampoDefinicion", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", null)
                        .WithMany("CamposDefinicion")
                        .HasForeignKey("TipoOrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CatalogoServicio", b =>
                {
                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "Cliente")
                        .WithMany()
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.Servicio", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CatalogoServicio", "CatalogoServicio")
                        .WithMany("Servicios")
                        .HasForeignKey("CatalogoServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CatalogoServicio");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.ServicioMaterial", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.Servicio", null)
                        .WithMany("MaterialesTeoricos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.ServicioPaso", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.Servicio", null)
                        .WithMany("Pasos")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.SucursalServicio", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.Servicio", null)
                        .WithMany("SucursalesHabilitadas")
                        .HasForeignKey("ServicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", b =>
                {
                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteFacturacion");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteServicio")
                        .WithMany()
                        .HasForeignKey("ClienteServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoCierre")
                        .WithMany()
                        .HasForeignKey("MotivoCierreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", "TipoOrden")
                        .WithMany()
                        .HasForeignKey("TipoOrdenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Recursos.ZonaOperativa", "ZonaOperativa")
                        .WithMany()
                        .HasForeignKey("ZonaOperativaId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ClienteFacturacion");

                    b.Navigation("ClienteServicio");

                    b.Navigation("MotivoCierre");

                    b.Navigation("TipoOrden");

                    b.Navigation("ZonaOperativa");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoMaterial", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Materiales")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", "OrdenTrabajoVisita")
                        .WithMany()
                        .HasForeignKey("OrdenTrabajoVisitaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("OrdenTrabajoVisita");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoTarea", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoRechazo")
                        .WithMany()
                        .HasForeignKey("MotivoRechazoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Tareas")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", "TarifarioRegla")
                        .WithMany()
                        .HasForeignKey("TarifarioReglaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", "TipoTarea")
                        .WithMany()
                        .HasForeignKey("TipoTareaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotivoRechazo");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("TarifarioRegla");

                    b.Navigation("TipoTarea");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.MotivoIncidencia", "MotivoCancelacion")
                        .WithMany()
                        .HasForeignKey("MotivoCancelacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", "OrdenTrabajo")
                        .WithMany("Visitas")
                        .HasForeignKey("OrdenTrabajoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Recursos.RecursoTecnico", "RecursoTecnico")
                        .WithMany()
                        .HasForeignKey("RecursoTecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MotivoCancelacion");

                    b.Navigation("OrdenTrabajo");

                    b.Navigation("RecursoTecnico");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisitaEvidencia", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", "OrdenTrabajoVisita")
                        .WithMany("Evidencias")
                        .HasForeignKey("OrdenTrabajoVisitaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdenTrabajoVisita");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Recursos.RecursoTecnico", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Recursos.ZonaOperativa", "ZonaOperativa")
                        .WithMany()
                        .HasForeignKey("ZonaOperativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ZonaOperativa");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifaServicio", b =>
                {
                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", "TipoTareaServicio")
                        .WithMany()
                        .HasForeignKey("TipoTareaServicioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ClienteFacturacion");

                    b.Navigation("TipoTareaServicio");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", b =>
                {
                    b.HasOne("BubbaBag.Modules.Crm.Domain.Clientes.Cliente", "ClienteFacturacion")
                        .WithMany()
                        .HasForeignKey("ClienteFacturacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClienteFacturacion");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.TarifarioRegla", b =>
                {
                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", "Tarifario")
                        .WithMany("Reglas")
                        .HasForeignKey("TarifarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoTareaServicio", "TipoTareaServicio")
                        .WithMany()
                        .HasForeignKey("TipoTareaServicioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tarifario");

                    b.Navigation("TipoTareaServicio");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.CatalogoServicio", b =>
                {
                    b.Navigation("Servicios");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.Servicio", b =>
                {
                    b.Navigation("MaterialesTeoricos");

                    b.Navigation("Pasos");

                    b.Navigation("SucursalesHabilitadas");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Mantenimientos.TipoOrdenTrabajo", b =>
                {
                    b.Navigation("CamposDefinicion");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajo", b =>
                {
                    b.Navigation("Materiales");

                    b.Navigation("Tareas");

                    b.Navigation("Visitas");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.OrdenesTrabajo.OrdenTrabajoVisita", b =>
                {
                    b.Navigation("Evidencias");
                });

            modelBuilder.Entity("BubbaBag.Modules.ServicioCampo.Domain.Tarifarios.Tarifario", b =>
                {
                    b.Navigation("Reglas");
                });
#pragma warning restore 612, 618
        }
    }
}
