import { makeStyles, tokens } from '@fluentui/react-components';
import { semanticTokens } from './semanticTokens';

/** Clases compartidas por los flujos de importación Excel/CSV. */
export const useD365ImportStyles = makeStyles({
  column: { display: 'flex', flexDirection: 'column' },
  resultColumn: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalM, marginBottom: tokens.spacingVerticalL },
  muted: { color: tokens.colorNeutralForeground3 },
  mutedSubtle: { color: tokens.colorNeutralForeground4 },
  neutral: { color: tokens.colorNeutralForeground2 },
  success: { color: semanticTokens.status.success },
  danger: { color: semanticTokens.status.dangerSubtle },
  brand: { color: semanticTokens.status.info },
  brandIcon: { color: tokens.colorCompoundBrandForeground1 },
  successIcon: { color: semanticTokens.status.success },
  hiddenInput: { display: 'none' },
  fileDetailsRow: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalM },
  stepArrow: { color: tokens.colorNeutralForeground4 },
  analysisRow: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalM, padding: tokens.spacingVerticalM },
  mappingHeader: {
    display: 'grid',
    gridTemplateColumns: '1fr 28px 1.4fr',
    padding: '4px 10px',
    fontWeight: tokens.fontWeightSemibold,
    fontSize: tokens.fontSizeBase200,
    color: tokens.colorNeutralForeground3,
  },
  overflowHidden: { overflow: 'hidden' },
  blockText: { display: 'block' },
  centered: { display: 'flex', justifyContent: 'center' },
  summarySection: { marginTop: tokens.spacingVerticalL, borderTop: `1px solid ${tokens.colorNeutralStroke2}`, paddingTop: tokens.spacingVerticalM },
  summaryList: { margin: 0, paddingLeft: '20px', fontSize: tokens.fontSizeBase200 },
  resultMetricsGrid: { display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: tokens.spacingHorizontalM, textAlign: 'center' },
  metricCard: { backgroundColor: tokens.colorNeutralBackground2, padding: tokens.spacingVerticalM, borderRadius: tokens.borderRadiusMedium },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(100px, 1fr))',
    gap: tokens.spacingHorizontalS,
    padding: '10px 14px',
    backgroundColor: tokens.colorNeutralBackground2,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  resultHeading: { display: 'block', marginBottom: tokens.spacingVerticalS },
  tableRowNumber: { width: '50px' },
  tableCode: { width: '120px' },
  codeCell: { fontFamily: tokens.fontFamilyMonospace, fontWeight: tokens.fontWeightSemibold },
  upsertContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 12px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusMedium,
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  upsertCopy: { display: 'flex', flexDirection: 'column', gap: tokens.spacingVerticalXXS },
  filenameRow: { display: 'flex', alignItems: 'center', gap: tokens.spacingHorizontalM },
  rightAligned: { marginLeft: 'auto' },
});
