import { ApplicationConfig, inject, provideBrowserGlobalErrorListeners, provideEnvironmentInitializer } from '@angular/core';
import { provideRouter } from '@angular/router';
import { routes } from './app.routes';
import { provideHttpClient, withInterceptors, withXhr } from '@angular/common/http';
import { authInterceptor } from './core/interceptors/auth.interceptor';
import { errorInterceptor } from './core/interceptors/error.interceptor';
import { NzConfig, NzConfigService, provideNzConfig } from 'ng-zorro-antd/core/config';
import { provideNzIcons } from 'ng-zorro-antd/icon';
import { NZ_I18N, es_ES } from 'ng-zorro-antd/i18n';
import { registerLocaleData } from '@angular/common';
import es from '@angular/common/locales/es';
import {
  AppstoreOutline,
  LogoutOutline,
  TeamOutline,
  ShoppingCartOutline,
  DatabaseOutline,
  UserOutline,
  DollarOutline,
  ShopOutline,
  BarChartOutline,
  SettingOutline,
  ArrowRightOutline,
  SunOutline,
  MoonOutline,
  ClockCircleOutline,
  CalendarOutline,
  UserAddOutline,
  SolutionOutline,
  LineChartOutline,
  PieChartOutline,
  HomeOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MenuOutline,
  BarsOutline,
  CloseOutline,
  UpOutline,
  DownOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  SearchOutline,
  LockOutline,
  DashboardOutline,
  ArrowLeftOutline,
  CheckOutline,
  MailOutline,
  PhoneOutline,
  UserDeleteOutline,
  ReloadOutline,
  FilterOutline,
  ExclamationCircleOutline,
  FileTextOutline,
  AuditOutline,
  TagsOutline,
  SwapOutline,
  CarOutline,
  AccountBookOutline,
  PayCircleOutline,
  FundOutline,
  BulbOutline,
  DownloadOutline,
  UploadOutline,
  FileExcelOutline,
  EllipsisOutline,
  TableOutline,
  ColumnWidthOutline,
  SaveOutline,
} from '@ant-design/icons-angular/icons';
import { provideNzDateFnsAdapter } from 'ng-zorro-antd/core/time';

registerLocaleData(es);

const icons = [
  AppstoreOutline,
  LogoutOutline,
  TeamOutline,
  ShoppingCartOutline,
  DatabaseOutline,
  UserOutline,
  DollarOutline,
  ShopOutline,
  BarChartOutline,
  SettingOutline,
  ArrowRightOutline,
  SunOutline,
  MoonOutline,
  ClockCircleOutline,
  CalendarOutline,
  UserAddOutline,
  SolutionOutline,
  LineChartOutline,
  PieChartOutline,
  HomeOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  MenuOutline,
  BarsOutline,
  CloseOutline,
  UpOutline,
  DownOutline,
  PlusOutline,
  EditOutline,
  DeleteOutline,
  SearchOutline,
  LockOutline,
  DashboardOutline,
  ArrowLeftOutline,
  CheckOutline,
  MailOutline,
  PhoneOutline,
  UserDeleteOutline,
  ReloadOutline,
  FilterOutline,
  ExclamationCircleOutline,
  FileTextOutline,
  AuditOutline,
  TagsOutline,
  SwapOutline,
  CarOutline,
  AccountBookOutline,
  PayCircleOutline,
  FundOutline,
  BulbOutline,
  DownloadOutline,
  UploadOutline,
  FileExcelOutline,
  EllipsisOutline,
  TableOutline,
  ColumnWidthOutline,
  SaveOutline,
];

const ngZorroConfig: NzConfig = {
  theme: {
    primaryColor: '#0f6cbd', // Color primario global de acento (ej. Fluent Blue #0078d4, Emerald #107c41, etc.)
    errorColor: '#d13438',
    warningColor: '#ffaa00',
    successColor: '#107c41',
    infoColor: '#0078d4',
  },
};

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideRouter(routes),
    provideHttpClient(withXhr(), withInterceptors([authInterceptor, errorInterceptor])),
    provideNzConfig(ngZorroConfig),
    provideEnvironmentInitializer(() => inject(NzConfigService)),
    provideNzIcons(icons),
    { provide: NZ_I18N, useValue: es_ES },
    provideNzDateFnsAdapter(),
  ],
};
